from __future__ import annotations

import json
import re
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATED_TABLE = REPO_ROOT / "paper" / "generated" / "main_benchmark_table.tex"
MAIN_TEX = REPO_ROOT / "paper" / "main.tex"
CANONICAL_TABLE_JSON = (
    REPO_ROOT
    / "artifacts"
    / "main_benchmark"
    / "table_3dof_paper_benchmark_stage3_20260412.json"
)
CANONICAL_BENCHMARK_JSON = (
    REPO_ROOT
    / "artifacts"
    / "main_benchmark"
    / "three_dof_benchmark_paper9suite_full5profile_bc32x32_stage3_20260412.json"
)
GENERATED_HEADER = (
    "% Generated by scripts/export/export_paper_only_sim_benchmark_table.py; "
    "do not edit manually."
)


LATEX_TO_SUITE = {
    "PPO w/o BC": "ppo_no_bc",
    "BC-only": "bc_only_stable_r32_p32",
    "Fixed-impedance RL": "fixed_impedance_rl_stable_r32_p32",
    "BC$\\rightarrow$PPO": "repaired_mainline_bc_to_ppo",
    "DAPG-lite": "dapg_lite_repaired_mainline",
}
CLASS_COLUMNS = ("baseline", "high_friction", "noisy_force")


def _parse_latex_rows() -> dict[str, list[str]]:
    rows: dict[str, list[str]] = {}
    for line in GENERATED_TABLE.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if " & " not in stripped or stripped.startswith("Method"):
            continue
        cells = [cell.strip() for cell in stripped.rstrip("\\").split("&")]
        rows[cells[0]] = cells[1:]
    return rows


def _mean_pm_cell(mean: float, std: float, *, digits: int) -> str:
    return f"${mean:.{digits}f} \\pm {std:.{digits}f}$"


def _metric_cell(row: dict, metric_name: str, *, digits: int) -> str:
    stats = row["five_profile_statistics"][metric_name]
    return _mean_pm_cell(float(stats["mean"]), float(stats["std"]), digits=digits)


def test_main_tex_includes_generated_table_body() -> None:
    manuscript = MAIN_TEX.read_text(encoding="utf-8")
    table_start = manuscript.index("\\label{tab:main_benchmark}")
    table_end = manuscript.index("\\end{table}", table_start)
    main_table_block = manuscript[table_start:table_end]

    assert "\\input{generated/main_benchmark_table.tex}" in manuscript
    assert "Fixed-impedance RL &" not in main_table_block
    assert "DAPG-lite &" not in main_table_block


def test_generated_latex_table_matches_canonical_json() -> None:
    payload = json.loads(CANONICAL_TABLE_JSON.read_text(encoding="utf-8"))
    latex_text = GENERATED_TABLE.read_text(encoding="utf-8")
    assert latex_text.startswith(GENERATED_HEADER)
    latex_rows = _parse_latex_rows()
    json_rows = {row["suite_name"]: row for row in payload["suite_rows"]}

    for latex_name, suite_name in LATEX_TO_SUITE.items():
        row = json_rows[suite_name]
        cells = latex_rows[latex_name]
        for cell, class_name in zip(cells[:3], CLASS_COLUMNS):
            class_metrics = row["class_success_statistics"][class_name]
            assert cell == _mean_pm_cell(
                float(class_metrics["mean"]),
                float(class_metrics["std"]),
                digits=2,
            )
        assert cells[3] == _metric_cell(row, "success_rate", digits=3)
        assert cells[4] == _metric_cell(row, "jam_rate", digits=3)
        assert cells[5] == _metric_cell(row, "mean_final_distance_mm", digits=3)
        assert cells[6] == _metric_cell(row, "mean_peak_contact_force_n", digits=3)
        assert cells[7] == _metric_cell(row, "mean_contact_steps", digits=1)


def test_final_distance_is_converted_from_meters_to_millimeters() -> None:
    payload = json.loads(CANONICAL_TABLE_JSON.read_text(encoding="utf-8"))
    benchmark = json.loads(CANONICAL_BENCHMARK_JSON.read_text(encoding="utf-8"))
    row = next(row for row in payload["suite_rows"] if row["suite_name"] == "bc_only_stable_r32_p32")
    latex_rows = _parse_latex_rows()
    final_distance_cell = latex_rows["BC-only"][5]

    raw_mm = float(row["five_profile_statistics"]["mean_final_distance_mm"]["mean"])
    raw_meters = [
        seed_payload["mean_final_distance"]
        for profile_payload in benchmark["learned_results"]["bc_only_stable_r32_p32"][
            "eval_results"
        ].values()
        for seed_payload in profile_payload["per_seed"]
    ]
    assert raw_mm == pytest.approx(
        sum(raw_meters) / len(raw_meters) * 1000.0
    )
    assert final_distance_cell == _mean_pm_cell(raw_mm, 0.008, digits=3)
